package com.example.hackathon;


import java.sql.Timestamp;
import java.util.Calendar;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.hackathon.Merchant;
import com.example.hackathon.MastTran;
import com.example.hackathon.MastTransfer;
import com.example.hackathon.Transaction;
import com.example.hackathon.FindCreate;
import com.example.hackathon.CardMerchLog;
import com.example.hackathon.UserRepository;
import com.example.hackathon.MastTranRepository;
import com.example.hackathon.MastTransferRepository;
import com.example.hackathon.MerchantRepository;
import com.example.hackathon.FindCreateRepository;
import com.example.hackathon.CardMerchLogRepository;
import com.google.gson.Gson;


@Controller    // This means that this class is a Controller
 // This means URL's start with /demo (after Application path)
public class MyController {
	
	Calendar calendar = Calendar.getInstance();
	Timestamp currentTimestamp = new java.sql.Timestamp(calendar.getTime().getTime());
	String currTimestamp=currentTimestamp.toString();
	
	Transaction t;
	Merchant m;
	MastTran mt;
	MastTransfer mtran;
	FindCreate findcreate;
	CardMerchLog cardmerchlog;
	Transaction t1;
	TTSWatson tts=new TTSWatson();
	 String json="";
	 String activity="";
	
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@Autowired
	private MerchantRepository merchRepository;
	
	@Autowired
	private MastTransferRepository masttransferRepository;
	
	@Autowired
	private MastTranRepository mastertransactionRepository;
	
	@Autowired
	private FindCreateRepository findcreateRepository;
	
	@Autowired
	private CardMerchLogRepository cardmerchlogRepository;
	
	@RequestMapping(path="/demo/transactionview",method=RequestMethod.GET)
	public String transactionview() {
	return "transactionview";
}

	 @RequestMapping(value="/demo/transactionview")
	 @ResponseBody
	 public String addNewUser(@RequestParam("pan") String pan,@RequestParam("merchid") String merchid,@RequestParam("billamt1") String billamt1,@RequestParam("amtpaid") String amtpaid,Model model) {
		json="";
		Long    pan1=Long.valueOf(pan);
		Long    merid=Long.valueOf(merchid);
		Integer billamt=Integer.valueOf(billamt1);
		Integer billpd=Integer.valueOf(amtpaid);
		Integer pointfetched;
		Integer pointsgiven;
		Integer valuefetched;
		Integer valuegiven;
		Integer valuetobepaid;
		String message="";
		Float merrate;
		Integer wallvalbefore;
		Integer wallvalafter;
		String statreason="";
		
		
		
		try {
			m = merchRepository.findBymerchid(merid);
			Float mrrate=m.getmrate().floatValue();
			merrate=(mrrate/10.0f);
			
		}
		catch(Exception e)
		{
			
			message="Merchant with the entered ID is not associated with Discover network";
			activity="Transaction was not successful because your merchant id was not part of the loyalty rewards programme for Discover";
			cardmerchlog=new CardMerchLog(merid,activity,currTimestamp);
			cardmerchlogRepository.save(cardmerchlog);
			model.addAttribute("message",message);
			tts.playSound(message);
			json=createjson(model);
			return json;
			
		}
		
		
		try {
		      t = userRepository.findBypan(pan1);
		      
		      pointfetched=t.getpoints();
		      valuefetched=t.getvalue();
		      wallvalbefore=valuefetched;
		      
		      if(billamt.intValue()==billpd.intValue())
		      {     
		    	    pointsgiven=(int) (billamt*merrate);
		    	    valuegiven=(Integer)((pointsgiven/10));
		    	    pointfetched=pointfetched + pointsgiven;
			        valuefetched=valuefetched+valuegiven;
			        wallvalafter=valuefetched;
		    	    t.setpoints(pointfetched);
					t.setvalue(valuefetched);
					userRepository.save(t);
					statreason="NA";
					mt=new MastTran(pan1,merid,billamt,billpd,valuegiven,0,wallvalbefore,wallvalafter,currTimestamp,"SUCCESSFUL",statreason);
					mastertransactionRepository.save(mt);
		    	    message="Your transaction has been completed successfully and "+ valuegiven + " $ have been credited to your digital wallet";
		    	    activity="The transaction was completed successfully. The merchant id was:-"+merid+".The transaction amount was:-"+billamt+" $.The amount entered was:-"+billpd+" $.The value added to your wallet was:-"+valuegiven+" $. The value in your wallet before this transaction was:-"+wallvalbefore+" $.The value in your wallet after this transaction was:-"+wallvalafter+ " $.";
		    	    cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
					cardmerchlogRepository.save(cardmerchlog);
		    	    model.addAttribute("message",message);
		    	    model.addAttribute("message1","alert alert-info");
		      }
		      
		      if(billpd.intValue()<billamt.intValue())
		      {valuetobepaid=billamt-billpd;
		       if(valuefetched.intValue()>=valuetobepaid.intValue())
		       {   
		    	    valuefetched=valuefetched-valuetobepaid;
		    	    pointsgiven=(int)(billamt*merrate);
		    	    valuegiven=(Integer)((pointsgiven/10));
		    	    pointfetched=pointfetched + pointsgiven;
			        valuefetched=valuefetched+valuegiven;
			        wallvalafter=valuefetched;
		    	    t.setpoints(pointfetched);
					t.setvalue(valuefetched);
					userRepository.save(t);
					statreason="NA";
					mt=new MastTran(pan1,merid,billamt,billpd,valuegiven,valuetobepaid,wallvalbefore,wallvalafter,currTimestamp,"SUCCESSFUL",statreason);
					mastertransactionRepository.save(mt);
		    	    message="Your transaction has been completed successfully and "+ valuetobepaid +" $ have been deducted from your wallet";
		    	    activity="The transaction was completed successfully and  "+valuetobepaid+" $ were deducted from your wallet. The merchant id was:-"+merid+".The transaction amount was:-"+billamt+" $.The amount entered was:-"+billpd+" $.The value added to your wallet was:-"+valuegiven+" $. The value in your wallet before this transaction was:-"+wallvalbefore+" $.The value in your wallet after this transaction was:-"+wallvalafter+ " $.";
		    	    cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
					cardmerchlogRepository.save(cardmerchlog);
		    	    model.addAttribute("message",message);
		    	    model.addAttribute("message1","alert alert-info");
		    	}
		       else
		       {
		    	statreason="Wallet value insufficient by "+ (valuetobepaid-wallvalbefore)+" $";
		    	mt=new MastTran(pan1,merid,billamt,billpd,0,valuetobepaid,wallvalbefore,wallvalbefore,currTimestamp,"UNSUCCESSFUL",statreason);
				mastertransactionRepository.save(mt);
		       message= "Your wallet does not have sufficient balance";
		       activity="The transaction attempted was not successful because your wallet did not have sufficient balance by "+(valuetobepaid-wallvalbefore)+" $. The merchant id was:-"+merid+".The transaction amount was:-"+billamt+" $.The amount entered was:-"+billpd+" $.";
		       cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
		       cardmerchlog=new CardMerchLog(pan1,message,currTimestamp);
		       cardmerchlogRepository.save(cardmerchlog);
		       model.addAttribute("message",message);
		       model.addAttribute("message1","alert alert-info");
		      }	   
		      }	
		      
		      if(billpd.intValue()>billamt.intValue())
		      {
		    	  statreason="Extra amount entered by " + (billpd-billamt)+ " $";
		    	  mt=new MastTran(pan1,merid,billamt,billpd,0,0,wallvalbefore,wallvalbefore,currTimestamp,"UNSUCCESSFUL",statreason);
		    	  mastertransactionRepository.save(mt);
		    	  message="The value filled for the amount to be paid by card, exceeds the transaction amount. Please correct it.";
		    	  activity="Transaction was not successful because you had entered extra amount. The merchant id was:-"+merid+".The transaction amount was:-"+billamt+" $.The amount entered was:-"+billpd+" $.";
		    	  cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
				  cardmerchlogRepository.save(cardmerchlog);
		    	  model.addAttribute("message",message);
		      }
		    }
		    catch (Exception e) {
		    	
				message="The card number as entered does not exist";
				activity="The transaction was not successful because your card was not part of the loyalty rewards programme";
				cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
				cardmerchlogRepository.save(cardmerchlog);
				model.addAttribute("message",message);
				model.addAttribute("message1","alert alert-info");
		    }
		tts.playSound(message);
		json=createjson(model);
		return json;
		
	}
	
	@RequestMapping(path="/demo/transferview",method=RequestMethod.GET)
	public String transferview() {
	return "transferview";
	}
	
	@RequestMapping(path="/demo/addmerchant",method=RequestMethod.GET)
	public String loadmerchant() {
	return "addmerchant";
	}
	
	 @RequestMapping(value="/demo/transferview")
	 @ResponseBody
	  public String updateUser(@RequestParam("pan1") String pan1,@RequestParam("pan2") String pan2,@RequestParam("amt") String amt,Model model) {
		 	json="";
		    Long pan11=Long.valueOf(pan1);
		    Long pan21=Long.valueOf(pan2);
		 	Integer valuefetched1;
			Integer valuefetched2;
			Integer valuefetched1bef;
			Integer valuefetched2bef;
			Integer valamt=Integer.valueOf(amt);
			String statreason="";
			
		try {
	    	
			t = userRepository.findBypan(pan11);
	    	valuefetched1=t.getvalue();
	    	valuefetched1bef=valuefetched1;
	    }
	    catch (Exception ex) {
	        String message="The card number " + pan1+ " does not exist";
	        model.addAttribute("message",message);
	        activity="Transaction was not successful because your card number " + pan1+ " did not exist while transferring "+valamt+" $ to "+pan2;
	        cardmerchlog=new CardMerchLog(pan11,activity,currTimestamp);
			cardmerchlogRepository.save(cardmerchlog);
	        model.addAttribute("message1","alert alert-info");
	        tts.playSound(message);
	        json=createjson(model);
	    	return json;
	    }
        try {
	    	
			t1 = userRepository.findBypan(pan21);
	    	valuefetched2=t1.getvalue();
	    	valuefetched2bef=valuefetched2;
	    }
	    catch (Exception ex) {
	      
	      String message="The card number " + pan2+ " does not exist";
	      activity="Transaction was not successful because the card number " + pan2+ " did not exist while transferring "+valamt+" $ .";
	      cardmerchlog=new CardMerchLog(pan11,activity,currTimestamp);
		  cardmerchlogRepository.save(cardmerchlog);
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	    }
        if(valamt<valuefetched1)
        {	
        	valuefetched1=valuefetched1-valamt;
        	t.setvalue(valuefetched1);
        	userRepository.save(t);
			valuefetched2=valuefetched2+valamt;
        	t1.setvalue(valuefetched2);
        	userRepository.save(t1);
        	statreason="NA";
        	mtran=new MastTransfer(pan11,pan21,valamt,valuefetched1bef,valuefetched2bef,valuefetched1,valuefetched2,currTimestamp,"SUCCESSFUL",statreason);
			masttransferRepository.save(mtran);
			activity="Amount worth " + amt +" $ was transferred to " +pan21;
			cardmerchlog=new CardMerchLog(pan11,activity,currTimestamp);
			cardmerchlogRepository.save(cardmerchlog);
			activity="Amount worth " + amt +" $ was transferred from " +pan11;
			cardmerchlog=new CardMerchLog(pan21,activity,currTimestamp);
			cardmerchlogRepository.save(cardmerchlog);
			String message="Your account has been debited by "+ amt + " $" +" and the recipient's account has been credited by " + valamt+" $" ;
			model.addAttribute("message",message);
			model.addAttribute("message1","alert alert-info");
			tts.playSound(message);
			json=createjson(model);
			return json;
        }
	 else
	 {	
		statreason="Wallet value insufficient by " + (valamt-valuefetched1bef)+ " $";
     	mtran=new MastTransfer(pan11,pan21,valamt,valuefetched1bef,valuefetched2bef,valuefetched1bef,valuefetched2bef,currTimestamp,"UNSUCCESSFUL",statreason);
		masttransferRepository.save(mtran);
		
		 String message="Your account does not have sufficient balance to transfer this amount. Your current balance is " + valuefetched1 + " $";
		 activity="Transfer attempt worth "+valamt+ "$ was made to "+pan21+ ".However your wallet did not have sufficient balance. Your current balance then was " + valuefetched1 + " $";
		 cardmerchlog=new CardMerchLog(pan11,message,currTimestamp);
		 cardmerchlogRepository.save(cardmerchlog);
		 model.addAttribute("message",message);
		 model.addAttribute("message1","alert alert-info");
		 tts.playSound(message);
		 json=createjson(model);
		 return json;
	 }
        
	 }
	 
	 @RequestMapping(path="/demo/pointsview",method=RequestMethod.GET)
	 public String pointsview() {
	 return "pointsview";
	 }


	 @RequestMapping(value="/demo/pointsview")
	 @ResponseBody
	  public String checkpoints(@RequestParam("ypan") String pan,Model model) {
		json="";
		Long pan1=Long.valueOf(pan);
	    Integer valueinwallet;
	    try {
	      Transaction t = userRepository.findBypan(pan1);
	      valueinwallet = t.getvalue();
	    }
	    catch (Exception ex) {
	      String message="User not found";
	      activity="Your card was not part of the database while enquiring balance";
		  cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
		  cardmerchlogRepository.save(cardmerchlog);
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	    }
	    
	      findcreate=new FindCreate(pan1,"BALANCE INQUIRY",valueinwallet,currTimestamp);
		  findcreateRepository.save(findcreate);
		  String message="The total amount in your digtal wallet is : " + valueinwallet+" $";
		  activity="The total amount in your digtal wallet was : " + valueinwallet+" $ "+"while enquiring balance";
		  cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
		  cardmerchlogRepository.save(cardmerchlog);
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	  }
	 
	 @RequestMapping(value="/demo/cardcheck")
	 @ResponseBody
	  public String pointalert(@RequestParam("ypan") String pan,Model model) {
		json="";
		Long pan1=Long.valueOf(pan);
	    Integer valueinwallet;
	    try {
	      Transaction t = userRepository.findBypan(pan1);
	      valueinwallet = t.getvalue();
	    }
	    catch (Exception ex) {
	      String message="The card number as entered does not exist";
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      json=createjson(model);
	      return json;
	    }
	      String message="The total amount in the cardholder's digital wallet is : " + valueinwallet+" $";
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      json=createjson(model);
	      return json;
	  }
	 
	 @RequestMapping(value="/demo/merchcheck")
	 @ResponseBody
	  public String merchalert(@RequestParam("merchid") String merchid,Model model) {
		json="";
		Long merid=Long.valueOf(merchid);
	    Float mrate;
	    
	    try {
	    	m = merchRepository.findBymerchid(merid);
	    	Float merrate=m.getmrate().floatValue();
			mrate=(merrate/100.0f);
	    }
	    catch (Exception ex) {
	      String message="Merchant with the entered ID is not associated with Discover network";
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	    }
	      String message="The loyalty and rewards rate of the entered merchant is : " + mrate +" $";
	      model.addAttribute("message",message);
	      model.addAttribute("message1","alert alert-info");
	      json=createjson(model);
	      return json;
	  }
	 
	 @RequestMapping(value="/demo/merchview")
	 @ResponseBody
	  public String merchview(@RequestParam("merchid") String merchid,Model model) {
		json="";
		Long merid=Long.valueOf(merchid);
	    String mername="";
	    Integer merrate=0;
	    try {
	      Merchant m = merchRepository.findBymerchid(merid);
	      mername =m.getmerchname();
	      merrate=m.getmrate();    
	    }
	    catch (Exception ex) {

	    }

	      model.addAttribute("mername",mername);
	      model.addAttribute("merrate",merrate);
	      
	      json=createjson(model);
	      return json;
	  }
	 
	 @RequestMapping(path="/demo/addpan",method=RequestMethod.GET)
	 public String abc() {
	return "addpan";
	 }
	 
	 
	  @RequestMapping(value="/demo/addpan")
	  @ResponseBody
	  public String addnewpan(@RequestParam("pan") String pan,Model model){  
		  String message=" ";
		  json="";
		  Long pan1=Long.valueOf(pan);
		  try {
		      Transaction t = userRepository.findBypan(pan1);
		      t.getpan();
		      message="The card number already exists";
		      activity="Your card already existed and an attempt was made to again insert it in the central database";
		      cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
			  cardmerchlogRepository.save(cardmerchlog);
		      model.addAttribute("message",message);
		    }
		  catch(Exception e)
		  {t=new Transaction(pan1,0,0);
		  userRepository.save(t);
		  findcreate=new FindCreate(pan1,"CREATION",0,currTimestamp);
		  findcreateRepository.save(findcreate);
		  message="Your card has been successfully added to the loyalty rewards programme";
		  activity="Your card was successfully added to the loyalty rewards programme";
		  cardmerchlog=new CardMerchLog(pan1,activity,currTimestamp);
		  cardmerchlogRepository.save(cardmerchlog);
		  model.addAttribute("message",message);
		  model.addAttribute("message1","alert alert-info");
		  }
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	  }
	  
	  @RequestMapping(value="/demo/addmerchant")
	  @ResponseBody
	  public String addnewmerchant(@RequestParam("merchid") String merchid,@RequestParam("merchname") String merchname,@RequestParam("mrate") String mrate,Model model){  
		  String message=" ";
		  json="";
		  Long merid=Long.valueOf(merchid);
		  Integer merchrate=Integer.valueOf(mrate);
		  System.out.println(merchrate);
		  try {
		      m = merchRepository.findBymerchid(merid);
		      m.getmerchid();
		      m.setmerchid(merid);
		      m.setmerchname(merchname);
		      m.setmrate(merchrate);
		      merchRepository.save(m);
		      message="Merchant details have been successfully updated for "+merchname+" and now for every 100$ of transaction, user will get " + merchrate +" $";
		      activity="Your details were updated and after updation your name was:-"+merchname+" and rate was:-"+merchrate;
		      cardmerchlog=new CardMerchLog(merid,activity,currTimestamp);
			  cardmerchlogRepository.save(cardmerchlog);
		      model.addAttribute("message",message);
		    }
		  
		  catch(Exception e)
		  {m=new Merchant(merid,merchname,merchrate);
		  merchRepository.save(m);
		  message="Merchant details for "+merchname+" have been successfully added to the loyalty rewards programme and for every 100$ of transaction, user will get " + merchrate + " $";
		  activity="You were made part of the loyalty and rewards programme with name:-"+merchname+" and rate:-"+merchrate;
		  cardmerchlog=new CardMerchLog(merid,activity,currTimestamp);
		  cardmerchlogRepository.save(cardmerchlog);
		  model.addAttribute("message",message);
		  model.addAttribute("message1","alert alert-info");
		  }
	      tts.playSound(message);
	      json=createjson(model);
	      return json;
	  }
	  
	  @RequestMapping(path="/demo/transview",method=RequestMethod.GET)
		 public String viewtrans(Model model) {
		  List<Transaction> t3=userRepository.findAll();
		  model.addAttribute("transaction",t3);
		  return "transview";
		 }
	 
	  
	  public String createjson(Model model) 
	  {
		  try
	      {
	    	  Gson gson = new Gson();
	    	  json = gson.toJson(model);
	      }
	      catch(Exception e)
	      {}
	      return json;
		  
	  }
}
